version: '3.9'

services:
  locust_master:
    image: locustio/locust
    env_file:
      - .env
    ports:
     - 8089:8089
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://locust_master:8089

  locust_worker:
    image: locustio/locust
    env_file:
      - .env
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host locust_master
