version: '3.9'

volumes:
  huggingface_cache:
    external: false

services:
  encoder:
    build:
      context: .
      dockerfile: ./services/encoder/Dockerfile
    container_name: svr_se_encoder
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - huggingface_cache:/root/.cache/huggingface/hub/

  web:
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    container_name: svr_se_web
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./static:/home/app/static
    depends_on:
      - encoder
    ports:
      - 8080:8080
