version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: svr_se_redis
    env_file: ./.env
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./services/redis/data:/data
      - ./services/redis/redis-stack.conf:/redis-stack.conf
    restart: unless-stopped
  encoder:
    build: ./services/encoder
    env_file: ./.env
    volumes:
      - ./common:/home/common
      - ./models:/home/models
    restart: unless-stopped
  search_engine:
    build: ./services/search_engine
    env_file: ./.env
    volumes:
      - ./common:/home/common
    restart: unless-stopped
    depends_on:
      - redis
      - encoder
  web:
    build: ./services/web
    container_name: svr_se_web
    env_file: ./.env
    volumes:
      - ./common:/home/common
      - ./static:/home/app/static
    restart: unless-stopped
    depends_on:
      - redis
  nginx:
    build: ./services/nginx
    container_name: svr_se_nginx
    volumes:
      - ./static:/www/web/static
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - web