version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: svr_se_redis
    env_file: ./.env
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./services/redis/data:/data
      - ./services/redis/redis-stack.conf:/redis-stack.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
