version: '3.9'

volumes:
  huggingface_cache:
    external: false

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: svr_se_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  encoder:
    build:
      context: .
      dockerfile: ./services/encoder/Dockerfile
    container_name: svr_se_encoder
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - huggingface_cache:/root/.cache/huggingface/hub/

  web:
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    container_name: svr_se_web
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./static:/home/app/static
    depends_on:
      - encoder
    ports:
      - 8080:8080
